# Generated by Django 3.0.5 on 2020-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.CharField(default=True, max_length=250)),
                ('slug_title', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(max_length=250)),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_data', models.TextField()),
            ],
        ),
    ]
