# Generated by Django 3.0.5 on 2020-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='slug_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
