# Generated by Django 3.0.5 on 2020-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200429_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='banner_image',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
