# Generated by Django 3.0.5 on 2020-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='slug_title',
            field=models.SlugField(unique=True),
        ),
    ]
