# Generated by Django 3.0.5 on 2020-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20200501_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='slug_title',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
